### ISSUE TITLE
Allow creating workflow(s) by uploading Serverless Workflow definition file(s)

### ISSUE THREAD

**Issue by cdavernas** [serverlessworkflow/synapse#133]
**What would you like to be added**:

To allow creating workflow(s) by uploading a Serverless Workflow definition file(s)

**Why is this needed**:

Allows users to upload a file instead of copy/pasting JSON

**Comment by JBBianchi** [comment]
It requires an endpoint on the API to upload json/yaml/zip(or other archive formats)

**Comment by cdavernas** [comment]
@JBBianchi IMO no, it does not. I believe you should read that file locally, if possible, using the IWorkflowReader from the ServerlessWorkflow SDK. 

That way, we avoid contacting the back-end for nothing, and can do client-side validation first hand, before using the `ISynapseManagementApi.CreateWorkflowAsync` method.

WDYT?

**Comment by cdavernas** [comment]
> From my understanding, file upload could be use for "projects", with multiple files (workflow, subflows and other references/resources)

Yeah, that's a very valid point. I'm on it!

**Comment by cdavernas** [comment]
@JBBianchi My part's done ;)

![image](https://user-images.githubusercontent.com/16137162/169533149-a75aac23-0a65-4542-8012-008cf65f0a0b.png)
