### ISSUE TITLE
Serverless Workflow SDK models BSON serialization issue

### ISSUE THREAD

**Issue by cdavernas** [serverlessworkflow/synapse#144]
**What happened**:

Because the Serverless Workflow SDK models are not properly annotated with (MongoDB's) BSON attributes, the ser/des of `WorkflowDefinitions` will systematically fail, because:

- **Abstract classes cannot be resolved out of the box (ex: StateDefinition, SwitchCaseDefinition, ...).** This can be easily fixed by adding a method to register adequate `BsonClassMaps`.
- **Properties  of type `OneOf<T1,T2>` (Start, End, etc) are ignored because they are `protected`.** Fixing this can be done by going through all types defined in the ServerlessWorkflow SDK and add configuration for said properties.
- **Dynamic values are serialized as empty objects.** Implementing a custom serializer/deserializer is probably the best option to fix this.

**What you expected to happen**:

Serverless Workflow SDK models are properly serialized and deserialized.

**How to reproduce it**:

Write/read a `ServerlessWorkflow.SDK.Models.WorkflowDefinition` instance into/from MongoDB

**Comment by cdavernas** [comment]
I see two different strategies to address those issues:
1. Marking all the SDK models with the proper BSON attributes, meaning adding yet another dependency to the SDK by adding a reference to the `MongoDB.BSON` package, but users won't have to worry about a thing.
2. Do extensive `BsonClassMap` configuration in the MongoDB plugin. The SDK avoids another dependency, but remains challenging to use "out of the box" in a MongoDB use case

@tsurdilo @antmendoza @JBBianchi What do you thin?

**Comment by antmendoza** [comment]
I couldn't have said it better, agree with @JBBianchi.

**Comment by cdavernas** [comment]
@JBBianchi @antmendoza Yeah, it's unhappilly the best way to go indeed. On it!
