### ISSUE TITLE
Edge is not drawn between default data case and transition to state

### ISSUE THREAD

**Issue by cdavernas** [serverlessworkflow/synapse#147]
**What happened**:

The edge is not drawn between default data case and transition to state

**What you expected to happen**:

Edge is drawn between the default data case and the state it should transition to

**How to reproduce it**:

Create a `switch` state which use a default data condition configuring a transition to another state

**Comment by JBBianchi** [comment]
I think it has been closed by #210, can you confirm @cdavernas ?

**Comment by cdavernas** [comment]
@JBBianchi I can confirm I'm not longer facing the problem locally ;) Cheers!
