### ISSUE TITLE
Add feature to specify the version of synapse-worker

### ISSUE THREAD

**Issue by Andy-Wu-2022** [serverlessworkflow/synapse#158]
**What would you like to be added**:

Add feature to specify the version of synapse-worker

**Why is this needed**:

Currently, it is:

```
    image: ghcr.io/serverlessworkflow/synapse-worker:latest
    imagePullPolicy: IfNotPresent
```

By default, the version of synapse-worker will NOT update when updating the version of synapse itself.  It will possibly cause some inconsistency.

thanks.

**Comment by cdavernas** [comment]
@Andy-Wu-2022 Closing as you can now configure that in the following ways:

- Updating the `appsettings.json` file like so:
```json
{
   "kubernetes":{
      "workerPod":{
         #kubernetes pod config
      }
   }
}
```
- Using the `KUBERNETES__WORKERPOD__SPEC__CONTAINERS__0__IMAGE` environment variable
