### ISSUE TITLE
Add a UI to visualize details about Synapse such as version, plugins, etc.

### ISSUE THREAD

**Issue by cdavernas** [serverlessworkflow/synapse#184]
**What would you like to be added**:

Add a UI to visualize details about Synapse such as version, plugins, etc.

A big plus would be to view, manage and update plugins.

**Why is this needed**:

So far, there is no user-friendly, UI-based way of determining the versions of (and other details about) the various components Synapse is made out of.

**Comment by JBBianchi** [comment]
Do you have any guidance on how to retrieve the info ?

**Comment by cdavernas** [comment]
@JBBianchi I opened #227 and assigned it to myself to create the endpoints you need
