### ISSUE TITLE
Add button to delete workflow definitions and all related data

### ISSUE THREAD

**Issue by cdavernas** [serverlessworkflow/synapse#185]
**What would you like to be added**:

Add button to delete workflow definitions and all related data.

Just as for workflow instance deletion, a dialog asking for confirmation and offering a download option would be outstanding IMHO.

**Why is this needed**:

Would allow getting rid of obsolete workflow definitions (might just be one or more versions of a given workflow definition).

**Comment by JBBianchi** [comment]
@cdavernas it sounds good to me, is the backend ready yet ?

I assume some resulting archives could be quite big though, is that a concern?

Also, in the UI, the WF are grouped as the latest version. Should all the definitions be deleted at once if no version is specified or just the latest ?

**Comment by cdavernas** [comment]
@JBBianchi The API supports deletion, but does not yet provide a way to download the archive, which I opened #226 for.

> I assume some resulting archives could be quite big though, is that a concern?

We could allow for users to configure the archiving with `includeInstances`, `allVersions` vs `specificVersion`, etc.

@JBBianchi wdyt?

**Comment by cdavernas** [comment]
Closed as stale
