### ISSUE TITLE
Add ability to delete a correlation context

### ISSUE THREAD

**Issue by bvandewe** [serverlessworkflow/synapse#284]
**What would you like to be added**:

The ability to delete an existing context in a correlation. 

The API currently enables to DELETE a correlation altogether, but not its context(s). (thought there's an issue with the DELETE, separate ticket).

**Why is this needed**:

At this point, i'm not 100% sure how this happened, but a correlation context was not deleted automatically as expected and can hardly find the server logs

This is low priority as far as im concerned.

**Comment by cdavernas** [comment]
Closing as implemented by #27
