### ISSUE TITLE
Add a mechanism to configure workers to ignore SSL certificate errors

### ISSUE THREAD

**Issue by cdavernas** [serverlessworkflow/synapse#30]
**What would you like to be added**:

Add a mechanism (such as an environment variable) to configure workers to ignore SSL certificate errors

**Why is this needed**:

In some cases, users might want to connect to services using self-signed (or invalid) certificates, and have no way to work around it.

**Comment by cdavernas** [comment]
@tsurdilo @ricardozanini @antmendoza @manuelstein It's arguable that such configuration could be defined at spec level. What do you guys think?

**Comment by cdavernas** [comment]
@bvandewe bump

**Comment by antmendoza** [comment]
Hi @cdavernas, to me sound like it has more to do with the infrastructure and with the engine than with the workflow definition itself.

**Comment by cdavernas** [comment]
@antmendoza Totally agree, but I wanted to make sure before going ahead with this ;)
