### ISSUE TITLE
Property actionFilter is not allowed.

### ISSUE THREAD

**Issue by whuanle** [serverlessworkflow/synapse#325]
**What happened**:
Property actionFilter is not allowed.
![image](https://user-images.githubusercontent.com/2189761/203505347-e6adb6a9-19ed-4125-ac6f-b12bea1b5cd2.png)

**How to reproduce it**:
json example:
```json
{
	"id": "simpleadd",
	"name": "simpleadd",
	"version": "0.1.0",
	"specVersion": "0.8",
	"functions": [{
		"name": "Increment Count Function",
		"operation": ".count += 1 | .count",
		"type": "expression"
	}],
	"start": "Initialize Count",
	"states": [{
			"name": "Initialize Count",
			"type": "inject",
			"data": {
				"count": 0
			},
			"transition": "Increment Count"
		},
		{
			"name": "Increment Count",
			"type": "operation",
			"actions": [{
				"functionRef": "Increment Count Function",
				"actionFilter": {
					"toStateData": "${ .count }"
				}
			}],
			"end": true
		}
	]
}
```

**Anything else we need to know?**:
When I save the json

![image](https://user-images.githubusercontent.com/2189761/203505676-9f45cdce-d715-4e1c-b9db-e7d043bc4ba0.png)
![image](https://user-images.githubusercontent.com/2189761/203505755-f04822a6-d50d-401c-87c3-e3e81a14bd1b.png)

**Comment by cdavernas** [comment]
@whuanle That's because it's `actionDataFilter` instead of `actionFilter`

**Comment by cdavernas** [comment]
Aouch, seems there's indeed a typo in the spec. Can u please report it?
