### ISSUE TITLE
Long running workflow appears stuck, no logs (calling subflows in sync mode)

### ISSUE THREAD

**Issue by bvandewe** [serverlessworkflow/synapse#326]
**What happened**:

A "parent" workflow appears stuck while executing a `foreach` state that calls a `subFlowRef`. The first two instances of the "child" flows completed successfully (got `Workflow executed` and `Application is shutting down...` in the workers' logs) but then no other instances were started and the parent flow appears stuck, nothing happens in the logs, no error/warning message at all. 

##### Parent/Caller flow

```
...
"states": [
...
{
      "name": "Reset Widgets",
      "type": "foreach",
      "inputCollection": ".forms",
      "actions": [
        {
          "name": "Create or Reset form widgets",
          "subFlowRef": {
            "invoke": "sync",
            "workflowId": "form-indicators-reset",
            "version": "latest"
          }
        }
      ],
      "iterationParam": "form",
      "end": true
    }
```

**What you expected to happen**:

With the input data, i expected 50x subflow instances to be created... Only two were started and executed successfully. 

**How to reproduce it**:

Try running a workflow that iteratively calls a subflow for more than 2 expected subflow instances...

**Anything else we need to know?**:

Will try in `async` mode and revert asap.

**Environment**:

Latest release ( `0.3.15`), K8s v1.22.3

**Comment by cdavernas** [comment]
@bvandewe Thanks for the feedback! I'll investigate asap ;)

**Comment by icableo** [comment]
@bvandewe @cdavernas same issue. 
If for example we have 4 iterations:

- Sync mode only execute 2 iterations.
- Async mode execute all iterations.

**Comment by cdavernas** [comment]
Closed as stale
