### ISSUE TITLE
Provide a set of sample workflow definitions to pick and run

### ISSUE THREAD

**Issue by tsurdilo** [serverlessworkflow/synapse#33]
**What would you like to be added**:

Add sample workflow definitions and example use-cases

**Why is this needed**:

For demos and getting started experience for new users, it would be nice to 
have a list of sample workflow definitions users can just pick and run (don't have to create themselves).

**Comment by cdavernas** [comment]
Closing this issue as won't fix because demo workflows can be picked from the website and be directly installed using `synctl`. 
Proceeding otherwise might imo create overhead for all the users who do not care about the demo.
