### ISSUE TITLE
Swagger UI doesnt seem to work at /api/doc

### ISSUE THREAD

**Issue by bvandewe** [serverlessworkflow/synapse#347]
**What happened**:

Swagger UI doesnt open and the UI returns `Sorry, there's nothing at this address.` when trying to open the route `/api/doc`. 
( Ref to https://github.com/serverlessworkflow/synapse/blob/452e8d711e443d6a10e92729ffbc2a78be7e9187/src/apps/Synapse.Server/Program.cs#L77 ).

This happens when running Synapse locally (http://localhost:42286/api/doc) so doesnt seem related to lower layers (k8s/istio/...).

**What you expected to happen**:

Would be great to be able to submit a workflow definition via the API, in case the UI doesnt accept one (like with https://github.com/serverlessworkflow/synapse/issues/346 ).

**How to reproduce it**:

**Anything else we need to know?**: v0.4.0

**Environment**: K8s & Docker compose

**Comment by cdavernas** [comment]
Fixed in #366
