### ISSUE TITLE
How to send cloudevent?

### ISSUE THREAD

**Issue by hongliang5316** [serverlessworkflow/synapse#348]
**What is the question**:
Is there a cloudevent receiving address? I tried configuring `SYNAPSE_CLOUDEVENTS_SINK_URI` and it didn’t seem to work

**Comment by hongliang5316** [comment]
@cdavernas Thanks for your answer, but it seems does not works for me.
<img width="1400" alt="image" src="https://user-images.githubusercontent.com/13626322/226880562-69c367d2-673d-47b7-99d0-9025b3ece182.png">

workflow use examples:
```json
{
  "id": "eventbasedgreeting",
  "name": "Event Based Greeting Workflow",
  "description": "Event Based Greeting",
  "version": "1.0.0",
  "specVersion": "0.8",
  "events": [
    {
      "name": "GreetingEvent",
      "source": "greetingEventSource",
      "type": "greetingEventType"
    }
  ],
  "functions": [
    {
      "name": "greetingFunction",
      "operation": "file://myapis/greetingapis.json#greeting",
      "type": "rest"
    }
  ],
  "start": "Greet",
  "states": [
    {
      "name": "Greet",
      "type": "event",
      "onEvents": [
        {
          "actions": [
            {
              "functionRef": {
                "refName": "greetingFunction",
                "arguments": {
                  "name": "${ .greet.name }"
                }
              }
            }
          ],
          "eventRefs": [
            "GreetingEvent"
          ],
          "eventDataFilter": {
            "data": "${ .greet }",
            "toStateData": "${ .greet }"
          }
        }
      ],
      "stateDataFilter": {
        "output": "${ .payload.greeting }"
      },
      "end": true
    }
  ]
}
```
when `running`,  but no trigger logs

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/13626322/226880988-bf67810c-b84b-4437-b04a-bfa493a3a77e.png">

@cdavernas  do you have any suggestions? thanks

**Comment by cdavernas** [comment]
By the way, the logs displayed in the UI only concern the workflow pod/process it is related to. In case of issues, you might one to check the server's, too.

**Comment by cdavernas** [comment]
@hongliang5316 Yes, indeed! You could submit a PR to fix it, but AFAIK its not the sole problem with those examples.

**Comment by hongliang5316** [comment]
@cdavernas 
Ok, I will do more tests later, and if I encounter problems, I will propose and make a PR.
