### ISSUE TITLE
Unknown error occurred while trying to verify integrity.

### ISSUE THREAD

**Issue by bvandewe** [serverlessworkflow/synapse#353]
**What happened**:

The UI fails to load and the console throws:

```
Failed to find a valid digest in the 'integrity' attribute for resource 'https://sj-keycloak.mydomain/auth/realms/Team/protocol/openid-connect/auth?approval_prompt=force&client_id=istio-oauth2-proxy&nonce=FVPy5vbHs_RyruHpJ0mVmM_5Y2q3YLaoy_weHKyx_FU&redirect_uri=https%3A%2F%2Fsynapse.mydomain.com%2Foauth2%2Fcallback&response_type=code&scope=openid+email+profile&state=pg1rNiXhqaR181YeB2lsrp_OuQlMKSllmE4M9_g8oQA%3A%2F_content%2FNeuroglia.Blazor.Dagre%2Flib%2Fdagre%2Fdagre.js' with computed SHA-256 integrity 'JiphR+yOuPwdRp1YkfnIe/7cceYyxHAkVdtPk5dHHzk='. The resource has been blocked.
03:01:37.658 Unknown error occurred while trying to verify integrity.
03:01:37.663 service-worker.js:22 Uncaught (in promise) TypeError: Failed to fetch
    at service-worker.js:22:54
    at async onInstall (service-worker.js:22:5)
```

Weirdly, this happens apparently quite randomly. If i unregister the service worker from the browser and fully reload the page, then it might work fine, not always. Still trying to identify conditions, triggers etc...

**What you expected to happen**: 

**How to reproduce it**: Not sure

**Anything else we need to know?**: i usually run multiple instances of the app in the same browser (on different tabs) but on different domains.  
Firewall may also be involved in our environments, maybe they dont like `.dll`'s? 

**Environment**: Kubernetes, Istio with OAuth2 proxy

**Comment by bvandewe** [comment]
Some refs: https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-7.0#diagnosing-integrity-problems

https://stackoverflow.com/questions/69926878/failed-to-find-a-valid-digest-in-the-integrity-attribute-for-resource-in-blazo

**Comment by cdavernas** [comment]
Closed as stale
