### ISSUE TITLE
Unable to save workflow in UI

### ISSUE THREAD

**Issue by rmanjusha** [serverlessworkflow/synapse#361]
Hi ,

I am new to workflows. I started with docker compose provided in source code (https://github.com/serverlessworkflow/synapse/blob/main/deployment/docker-compose/docker-compose.yml) and tried saving hello world workflow sample provided. When trying to save the work flow its not saving .

**Comment by JBBianchi** [comment]
Could you check the dev console of your browser for errors (and the server logs as well) ? In the current state of the issue, we do not have enough information to provide support.

**Comment by cdavernas** [comment]
Closed as stale
