### ISSUE TITLE
Function type : custom usage

### ISSUE THREAD

**Issue by mremadevi** [serverlessworkflow/synapse#364]
Can a function call .net  method using function type as 'custom' ?

**Comment by JBBianchi** [comment]
Not really. Functions in the Serverless Workflow spec are actually "serverless" functions, not "local" functions of your code. That being said, you could probably implement your own [`Processor`](https://github.com/serverlessworkflow/synapse/tree/main/src/apps/Synapse.Worker/Services/Processors). Know that we invision a new version of Synapse that should be way more flexible on the type of actions you could run but it's still in a conceptual phase (and I know it's been a while but we want to take our time to put the right pieces together).

That being said, may I ask which .NET method are you trying to call ?

**Comment by cdavernas** [comment]
@mremadevi With 1.0.0 Serverless Workflows enables you to run any process you'd like, using containers, scripts or shell. Another couple of weeks and a new Synapse release supporting said feature will see the day ;)
Does that answer your question?

**Comment by cdavernas** [comment]
@mremadevi I'm gonna assume my last comment answered your question and will therefore close this issue.
Feel free to reopen if need be ;)
