### ISSUE TITLE
synctl system install native failed on osx

### ISSUE THREAD

**Issue by wuxc** [serverlessworkflow/synapse#367]
**What happened**:
when i run 'synctl system install native', got an error like this:

$ ./synctl system install native
An error occurred trying to start process 'cmd.exe' with working directory '..../synctl-osx-x64'. No such file or directory

It seems os is wrong.

**What you expected to happen**:
install ok

**How to reproduce it**:
run install command on osx
$ ./synctl system install native

**Anything else we need to know?**:

**Environment**:

**Comment by cdavernas** [comment]
Hey @wuxc, thanks for reporting!

However, the bug you encountered is in a discontinued version of Synapse, and I won't be able to personally address it.
If you feel like contributing to branch `0.4.3`, though, you are more than welcome!

For the time being, I'll proceed and close this issue as won't fix.
