### ISSUE TITLE
Add CI/CD workflow to package Helm charts

### ISSUE THREAD

**Issue by cdavernas** [serverlessworkflow/synapse#368]
**What would you like to be added**:

Add a CI/CD workflow to package Helm charts.

**Why is this needed**:

Implementing this CI/CD workflow will enhance the robustness of the deployment processes and ensure that Helm charts are always ready for reliable and consistent deployments.

**Comment by robinson** [comment]
@cdavernas thanks for the interesting project firstly.
are there anyone working on this ticket? if not yet then could I support on that? I am intending to use github pages and Artifact Hub in github actions, is that ok?
Cheers,
Robin

**Comment by cdavernas** [comment]
@robinson No one's assigned to the task as of now. We gladly and warmly welcome your help!

**Comment by robinson** [comment]
cool, thanks @cdavernas. Then next favour, could you create these steps as following prerequisites:
<img width="350" alt="image" src="https://github.com/user-attachments/assets/b3c3e447-7c0d-462d-a36d-ae388cb8bb51">

**Comment by cdavernas** [comment]
I just did it! Let me know if I can do anything else!

**Comment by robinson** [comment]
https://github.com/serverlessworkflow/synapse/pull/450
solved with this PR.
