### ISSUE TITLE
Configure folder to injest static list of "startup workflows" 

### ISSUE THREAD

**Issue by alvin** [serverlessworkflow/synapse#417]
**What would you like to be added**:
* specify a folder to read for yml/json files containing workflows that auto-populate into Synapse on startup.

**Why is this needed**:
* It's a simple "lowest common denominator" way to implement/orchestrate a fully functional solution/backend using synapse 
* as a (potential) builder of an external system that would depend on Synapse, **I would require my full working solution config to be versioned intuitively in my main repository or monorepo** without depending on the Garnet backing store's persistence layer as the source of truth for system behaviours.   

**Additional sub-features/considerations (nice-to-haves)**:
* *include a default workflow config folder co-located near or as part of the orchestration config?*  (eg. docker-compose, k8s, etc) so that all of the "how we integrate synapse" stuff is clearly versioned together
* support *"forgetting" / overwriting Garnet-persisted workflow config* on startup when this config is enabled
* support *"flushing" runtime changes to the workflows from Garnet* out to the config folder/storage endpoint (actually I think I may have noticed some "export" features already?) 
* support for *"glob" style patterns to filter subsets of the folder* (eg. for use-cases where the workflows must be mixed in with other config files) 
* support for *varied targets (eg. subdirectories?) in different startup scenarios* (eg. multi-tenancy / other fancy scenarios)
* support for *external `object storage` as data source instead of filesystem* (eg. amazon s3 / azure blob storage, etc) 

@cdavernas I've added this one per our discussion as well. LMK what you think.

**Comment by cdavernas** [comment]
Sounds perfect! Great idea! Will do asap!
