### ISSUE TITLE
 Error Toast Message is Not Dismissible

### ISSUE THREAD

**Issue by sonathaj** [serverlessworkflow/synapse#447]
**Description**
When an error toast message appears in the Synapse UI, it currently lacks a dismiss button, preventing users from closing it.

**Steps to Reproduce**
1. Trigger an error in the Synapse UI that generates a toast message.
2. Message lacks a dismiss option.

**Expected Behavior**
The error toast message should include a dismiss button so users can close it manually if desired.

Thank you :)

**Comment by SonaThaj** [comment]
Hello Jean,

Yes exactly, it's the error message on the editor. Is there any way I can close it? 

Thanks for your quick response.

**Comment by JBBianchi** [comment]
Thanks for clarifying, I'll add a close button :)
