### ISSUE TITLE
Cannot run an instance of a workflow

### ISSUE THREAD

**Issue by anushapai23** [serverlessworkflow/synapse#456]
**What happened**:
I cloned this repo.
Ran the docker-compose up on docker-compose.build.yml
Created a test workflow in the UI
When I tried to run an instance, the instance wouldnt turn into running. It is struck at pending.

**What you expected to happen**:
I expected it to run

**Anything else we need to know?**:
The logs in docker, for the container api-1 is as follows:

Neuroglia.ProblemDetailsException: [404 - Not Found] Failed to find the specified resource 'synapse.io/v1/namespace/default/workflows/test'.

docker-compose.build.yml
**Environment**:
Running this using Docker Desktop and in Windows

**Comment by cdavernas** [comment]
Hello @anushapai23 and thanks for reporting! Would you mind providing a bit more info? Is the `operator` container running, and if so, does it has meaningful logs?

**Comment by anushapai23** [comment]
I see that the operator container starts and exits  in 6 seconds. I see the following in its logs :

2024-12-06 12:40:19    at Program.<Main>$(String[] args) in /src/src/operator/Synapse.Operator/Program.cs:line 74
2024-12-06 12:40:19    at Program.<Main>(String[] args)

**Comment by cdavernas** [comment]
@anushapai23 I'm not sure what you are copy/pasting from the operator,, but here's a sample log output:

```
[09:51:35] info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
[09:51:35] info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
[09:51:35] info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Dev\ServerlessWorkflow\synapse\src\operator\Synapse.Operator\bin\Debug\net9.0
```

**Comment by anushapai23** [comment]
I see the below error in operator. 

```
2024-12-06 18:22:23 [14:22:23] info: Microsoft.Hosting.Lifetime[0]
2024-12-06 18:22:23       Application started. Press Ctrl+C to shut down.
2024-12-06 18:22:23 [14:22:23] info: Microsoft.Hosting.Lifetime[0]
2024-12-06 18:22:23       Hosting environment: Production
2024-12-06 18:22:23 [14:22:23] info: Microsoft.Hosting.Lifetime[0]
2024-12-06 18:22:23       Content root path: /app
2024-12-06 18:26:07 [14:26:07] fail: Synapse.Runtime.Docker.Services.DockerRuntime[0]
2024-12-06 18:26:07       An error occurred while creating a new Docker process for workflow instance 'test-db14f8c040c5.default': Docker.DotNet.DockerApiException: Docker API responded with status code=InternalServerError, response=mkdir C:\Users\User: Access is denied.
2024-12-06 18:26:07
```

I am using the file docker-compose.yml

**Comment by anushapai23** [comment]
I tried running Dockerfile at /src/runner/Synapse.Runner/Dockerfile location locally.

Seeing this error now

```
Dockerfile:19
--------------------
  17 |     COPY ["src/api/Synapse.Api.Client.Core/Synapse.Api.Client.Core.csproj", "src/api/Synapse.Api.Client.Core/"]
  18 |     COPY ["src/core/Synapse.Core/Synapse.Core.csproj", "src/core/Synapse.Core/"]   
  19 | >>> COPY ["src/core/Synapse.Core.Infrastructure/Synapse.Core.Infrastructure.csproj", "src/core/Synapse.Core.Infrastructure/"]
  20 |     RUN dotnet restore "./src/runner/Synapse.Runner/Synapse.Runner.csproj"
  21 |     COPY . .
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref d3bf221b-1469-4cb6-b183-c29b401af04d::vfpjjoht1eilyft4soj1fr16e: "/src/core/Synapse.Core.Infrastructure/Synapse.Core.Infrastructure.csproj": not found
```

**Comment by cdavernas** [comment]
As you can see, path in the Dockerfile are relative to the solution's root, not to the `Synapse.Runner` directory. 

You therefore need to run the following command from Synapse's root directory (where the `src` folder is located):

```
docker build . -f src/runner/Synapse.Runner/Dockerfile
```

**Comment by anushapai23** [comment]
Now, I see the runner, runner:1.0.0-alpha5.3 in UI. However, the instances are still struck at pending

**Comment by cdavernas** [comment]
@anushapai23 Happy to hear! Mind sharing the changes you made, so that it may help others?

**Comment by anushapai23** [comment]
Sure. I am using Windows + Docker steup

In docker_compose.yaml, under the operator service, set 

SYNAPSE_RUNTIME_DOCKER_SECRETS_DIRECTORY: /run/secrets/synapse
DOCKER_HOST= tcp://localhost:2375
volumes:
      - ./secrets:/run/secrets/synapse
      
In the Synapse UI( api-1) :
In Services -> Opeartors -> operator

- Ensure that image version(1.0.0-alpha5.6) is same as the version tags of other services.
- The secrets/directory should rightly point to the local location. Eg - C:\Users\<User>\.......

With these changes, I was able to run the workflows locally in my Windows+ Docker Desktop
