### ISSUE TITLE
Enable standalone Synapse runner

### ISSUE THREAD

**Issue by JBBianchi** [serverlessworkflow/synapse#466]
**What would you like to be added**:
I would like the Synapse runner to support an option to execute workflows as a CLI tool, independent of the Synapse server API. This enhancement would allow the runner to handle workflow state internally without requiring interaction with the API, effectively enabling standalone execution. 

By default, the standalone runner should return only the final output of the workflow. However, an option to enable "verbose" mode or detailed logs with task execution history would be valuable for debugging or in-depth analysis.

**Why is this needed**:
This feature is essential for several reasons:

- *Facilitate Compliance Tests*: By allowing workflows to run in isolation, users can more easily integrate the Synapse runner into CI/CD pipelines to verify compliance with the Serverless Workflow CTK.
- *Broaden Accessibility*: Reducing the dependency on the API makes it easier for new users and contributors to experiment with workflows, accelerating adoption and feedback for the project.
- *Simplify Testing*: It provides a lightweight way for users to test workflows without needing to deploy the full Synapse infrastructure, including a server and database.

This enhancement would significantly improve the usability and flexibility of the Synapse runner while expanding its potential use cases.

**Comment by cdavernas** [comment]
Closed by https://github.com/serverlessworkflow/synapse/pull/470
