### ISSUE TITLE
CORS error when using a DNS other than localhost

### ISSUE THREAD

**Issue by ketseh** [serverlessworkflow/synapse#49]
**What happened**:

A CORS error is thrown by the dashboard

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:42286/api/ws/negotiate?negotiateVersion=1. (Reason: CORS request did not succeed). Status code: (null).

**What you expected to happen**:

No CORS error is thrown and the dashboard works as expected

**How to reproduce it**:

Run Synapse on a DNS other than localhost

**Anything else we need to know?**:

Probably origin is not used in one or more of the XHR requests (I got this twice on the single page reload).

**Comment by JBBianchi** [comment]
Probably comes from https://github.com/serverlessworkflow/synapse/blob/main/src/dashboard/Synapse.Dashboard/Program.cs#L62 (L42 also have some localhost hardcoded)
