### ISSUE TITLE
lack cli install url and docker image

### ISSUE THREAD

**Issue by xunfeng1980** [serverlessworkflow/synapse#7]
**What happened**:
docker pull synapse/operator:0.1.0
Error response from daemon: pull access denied for synapse/operator, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
**What you expected to happen**:
docker pull synapse/operator:0.1.0 success
**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
Darwin MacBook-Pro.local 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:27 PDT 2021; root:xnu-7195.141.2~5/RELEASE_ARM64_T8101 arm64

**Comment by cdavernas** [comment]
@xunfeng1980 Hello, and thanks for your repport!

Our docker account was blocked for a couple of months, so we couldn't upload the images on their repo. If you want the current version to work, you'll have to clone the repo and build the images localy.

I'm gonna fix that for upcoming release, which's an overhaul of the current version, which will run in self-hosted, embedded, Docker or Kubernetes environment.

**Comment by xunfeng1980** [comment]
@cdavernas I see, thank you。

**Comment by cdavernas** [comment]
@xunfeng1980 You can try the latest release, should be working as expected!
