### ISSUE TITLE
Extremely slow workflow details view

### ISSUE THREAD

**Issue by JBBianchi** [serverlessworkflow/synapse#77]
**What happened**:
After starting multiple instances, going to the workflow definitions' list and coming back to a workflow detail, the list of instances/graph takes multiple seconds to display!

**What you expected to happen**:
To be way faster

**Comment by JBBianchi** [comment]
@cdavernas > Could it be a deserialization issue ? Making the request is quite fast but it takes a lot of time for the result variable to be assigned.

![serialization](https://user-images.githubusercontent.com/72747835/167586303-ff407104-750f-4106-83ad-0b6fad4a6ecf.gif)

**Comment by cdavernas** [comment]
@JBBianchi What about performances when debug/remote debug (Blazor) is disabled? Still unsatisfying?
In addition, are you using persistence plugins?

**Comment by JBBianchi** [comment]
@cdavernas no persistence, I don't think it have anything to do with debugging. It's [await this.Serializer.DeserializeAsync<List<V1WorkflowInstance>>(json, cancellationToken)](https://github.com/serverlessworkflow/synapse/blob/main/src/apis/management/Synapse.Apis.Management.Http.Client/Services/SynapseHttpManagementApiClient.cs#L195) in the api client that hangs.

**Comment by cdavernas** [comment]
@JBBianchi Hasn't this been fixed, aside from `Dynamic` issue (which will be solved with .NET 7 and replacement of Newtonsoft)?

**Comment by JBBianchi** [comment]
@cdavernas the issue is still present to my knowledge. :crossed_fingers: for it to be solved with .NET 7 and System.Text.

**Comment by cdavernas** [comment]
Fixed the cause in `1.0.0-alpha1`, which was related to serialization optimisation issues (solved mostly by using System.Text.Json and getting rid of types such as Dynamic) and especially to design issues: workflow instance metadata returned by the API also contained the workflow input/output, and this for any and all activities.
