### ISSUE TITLE
Empty workflow list when navigating back to `Workflows` view

### ISSUE THREAD

**Issue by cdavernas** [serverlessworkflow/synapse#91]
**What happened**:

When coming back to the workflow list from within a given workflow's view, the list is empty, an no error is to be found in logs and/or requests.

**What you expected to happen**:

The list should display existing workflows

**How to reproduce it**:

Navigate to a specific workflow's view, then go back to the workflow list view using the breadcrumb, for example.

If it is, as I think, related to #90, you should first follow the latter's instructions on how to repro.

**Anything else we need to know?**:

This is probably linked to #90, as I could only reproduce it when it occurs

**Comment by JBBianchi** [comment]
I think this was a side effect of the exception raised in #90 . If not, reopen this issue with details.
